name: reunion-test-prod

services:
  mongo:
    image: mongo:8.0.4
    volumes:
      - mongo_data:/data/db
    networks:
      - reunion-test-prod-network
    restart: unless-stopped

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./Backend/.env
    volumes:
      - ../uploads/images:/app/uploads/images
    networks:
      - reunion-test-prod-network
    depends_on:
      - mongo

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./Frontend/.env
    volumes:
      - frontend_build:/app/dist
    networks:
      - reunion-test-prod-network
    depends_on:
      - backend

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - frontend_build:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - reunion-test-prod-network

volumes:
  mongo_data:
  uploaded_images:
  caddy_data:
  caddy_config:

networks:
  reunion-test-prod-network:
    driver: bridge
