name: reunion-test

services:
  mongo:
    image: mongo:8.0.4
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - reunion-test-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./Backend/.env
    volumes:
      - ./Backend:/app
      - /app/node_modules
      - ./local-uploads:/app/local-uploads
    networks:
      - reunion-test-network
    ports:
      - 4000:4000
    depends_on:
      - mongo

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./Frontend/.env
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    networks:
      - reunion-test-network
    ports:
      - 5173:5173
    command: npm run dev -- --host
    depends_on:
      - backend

volumes:
  mongo_data:
  uploaded_images:
networks:
  reunion-test-network:
    driver: bridge
